### ISSUE TITLE
增加读取邮箱文件去判断存活

### ISSUE THREAD

**Issue by fanyibo2009** [Tzeross/verifyemail#1]
目前直接在文件中改邮箱有点麻烦，希望师傅可以加一个功能。不过自己也可以加。嘻嘻

**Comment by fanyibo2009** [comment]
修改完成。添加两部分
第一部分：
if __name__ == '__main__':
    path = os.getcwd()
    f = open(path+'/mail.txt', 'r') 
    result=[]
    for line in f.readlines():
        line = line.strip('\n')
        result.append(line)
    final_list = verify_istrue(result)
    print(final_list)

第二部分：
if send_from[0] == 250 or send_from[0] == 451:
                final_res[need_verify] = True  # 存在
                path = os.getcwd()
                f = open(path+'/ok.txt', 'a+') 
                f.write(need_verify+"\n")
                f.close()
                print(need_verify)

最后在同级目录下生成ok.txt。内容为存活邮箱

**Comment by clhaaaa** [comment]
绝活，issue里面贴代码，一点缩进也没有。
